import type { Army } from './Army';

export const borgoArmy: Army = {
  name: 'Borgo',
  id: 'borgo',
  tokens: [
    'borgo-sztab',
    'borgo-bitwa',
    'borgo-bitwa',
    'borgo-bitwa',
    'borgo-bitwa',
    'borgo-bitwa',
    'borgo-bitwa',
    'borgo-ruch',
    'borgo-granat',
    'borgo-mutek',
    'borgo-mutek',
    'borgo-mutek',
    'borgo-mutek',
    'borgo-mutek',
    'borgo-mutek',
    'borgo-nozownik',
    'borgo-nozownik',
    'borgo-nozownik',
    'borgo-nozownik',
    'borgo-sieciarz',
    'borgo-sieciarz',
    'borgo-supermutant',
    'borgo-silacz',
    'borgo-silacz',
    'borgo-zabojca',
    'borgo-zabojca',
    'borgo-medyk',
    'borgo-oficer',
    'borgo-oficer',
    'borgo-superoficer',
    'borgo-zwiadowca',
    'borgo-zwiadowca',
  ],
};
