import type { Army } from './Army';

export const molochArmy: Army = {
  name: 'Moloch',
  id: 'moloch',
  tokens: [
    'moloch-sztab',
    'moloch-bitwa',
    'moloch-bitwa',
    'moloch-bitwa',
    'moloch-bitwa',
    'moloch-ruch',
    'moloch-odepchniecie',
    'moloch-odepchniecie',
    'moloch-odepchniecie',
    'moloch-odepchniecie',
    'moloch-odepchniecie',
    'moloch-bomba',
    'moloch-bloker',
    'moloch-bloker',
    'moloch-cyborg',
    'moloch-cyborg',
    'moloch-dzialkogaussa',
    'moloch-juggernaut',
    'moloch-klaun',
    'moloch-lowca',
    'moloch-lowca',
    'moloch-obronca',
    'moloch-opancerzonylowca',
    'moloch-opancerzonylowca',
    'moloch-opancerzonywartownik',
    'moloch-rozpruwacz',
    'moloch-sieciarz',
    'moloch-szturmowiec',
    'moloch-wartownik',
    'moloch-mozg',
    'moloch-oficer',
    'moloch-zwiadowca',
    'moloch-medyk',
    'moloch-medyk',
    'moloch-matka',
  ],
};
